# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: SMART HANDLERS API
  description: Smart HANDLERS API
  version: "1.0.0"
# the domain of the service
host: nd
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
